import React from 'react';
import PropTypes from 'prop-types';
import Head from 'next/head';
import styles from './MainLayout.module.css';

export default function MainLayout({
    children
}) {
    return (
        <div className={styles.container}>
            <Head>
                <title>my-talks example for Cloud Run</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={styles.main}>
                {children}
            </main>
        </div>
    );
}


MainLayout.propTypes = {
    children : PropTypes.any.isRequired
};

