import React from 'react';
import PropTypes from 'prop-types';
import Head from 'next/head';
import styles from './MainLayout.module.css';
import Header from './blocks/Header';

export default function MainLayout({
    children
}) {
    return (
        <React.Fragment>
            <Head>
                <title>my-talks example for Cloud Run</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={styles.main}>
                <div className={styles.headerWrapper}>
                    <div className={styles.container}>
                        <Header />
                    </div>
                </div>
                <div className={styles.container}>
                    {children}
                </div>
            </main>
        </React.Fragment>
    );
}


MainLayout.propTypes = {
    children : PropTypes.any.isRequired
};

